//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expence
    {
        public int Id { get; set; }
        public System.DateTime DateExpence { get; set; }
        public string ExpenceDescription { get; set; }
        public decimal Summa { get; set; }
        public int TypeExpenceId { get; set; }
    
        public virtual TypeExpence TypeExpences { get; set; }
    }
}
