//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profit
    {
        public int Id { get; set; }
        public System.DateTime ProfDate { get; set; }
        public string ProfDescription { get; set; }
        public Nullable<decimal> SumEntrance { get; set; }
        public Nullable<decimal> SumAdded { get; set; }
        public int PersonId { get; set; }
    
        public virtual Person Persons { get; set; }
    }
}
