//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int Id { get; set; }
        public System.DateTime DateRevenue { get; set; }
        public string RevenueDescription { get; set; }
        public decimal SumRev { get; set; }
        public decimal Procent { get; set; }
        public int TypeRevenueId { get; set; }
    
        public virtual TypeRevenue TypeRevenues { get; set; }
    }
}
