//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FamilyCash
{
    using System;
    using System.Collections.Generic;
    
    public partial class Revenue
    {
        public int Id { get; set; }
        public System.DateTime RevDate { get; set; }
        public string RevDescription { get; set; }
        public decimal RevSum { get; set; }
        public decimal RevProcent { get; set; }
        public int TypeRevenueId { get; set; }
        public int PersonId { get; set; }
    
        public virtual TypeRevenue TypeRevenues { get; set; }
        public virtual Person Person_Revenue { get; set; }
    }
}
